### PR TITLE
Support python3.10 drop python3.7 support

### PR DESCRIPTION
**Pull request by carlculator**

### CODE REVIEW

**Review by TimoGuenther — COMMENTED** [review]
I am all for supporting Python 3.10, but please explain the hurry in dropping support for Python 3.7 as it has yet to reach its [end of life](https://endoflife.date/python).

**Comment by carlculator** [comment]
> I am all for supporting Python 3.10, but please explain the hurry in dropping support for Python 3.7 as it has yet to reach its [end of life](https://endoflife.date/python).

I don't mean to hurry. It's because some dependencies of this library (i.e. pandas) deprecated Python 3.7 in their latest stable versions. I'd like to keep up with the latest releases and I am to lazy to maintain two versions at the moment, especially when this library is still pre-alpha.

**Comment by TimoGuenther** [comment]
Are any features of the latest versions of these dependencies actually required? If not, it would be courteous to at least support Python 3.7 until its end of life. In any case, before eventually dropping support for Python 3.7, the most recent state of `develop` should be released as a public version to accommodate users of Python 3.7 with as many bug fixes and features as possible.

**Comment by carlculator** [comment]
> In any case, before eventually dropping support for Python 3.7, the most recent state of `develop` should be released as a public version to accommodate users of Python 3.7 with as many bug fixes and features as possible.

I definitely agree on that. So let's park this pull request until the rest is done.

**Comment by TimoGuenther** [comment]
Python 3.7 has recently reached its end of life.

**Pull request merged**
